import { Check, Database, FileText, Image, MoreHorizontal, PenLine, Plus, Tag } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import type { AppState, CreationTask } from '../../data'
import type { Route } from '../../types'
import type { ConfirmRequest } from '../../shared/contracts'
import { Modal, Toolbar } from '../../shared'
import { useTranslation } from '../../i18n'
import { uid } from '../../utils'

type Patch = (next: Partial<AppState>) => void

export function CreationPage({ state, patch, onCreate, onCreateTask, onInspectTask, navigate: _navigate, notify, onConfirm: _onConfirm }: { state: AppState; patch: Patch; onCreate: () => void; onCreateTask: (task?: CreationTask) => void; onInspectTask: (taskId: string) => void; navigate: (route: Route) => void; notify: (message: string) => void; onConfirm: (request: ConfirmRequest) => void }) {
  const { t: tr } = useTranslation(); const [search, setSearch] = useState('')
  const tasks = state.creationTasks.filter(item => `${item.name} ${item.keyword} ${tr(item.status)}`.toLowerCase().includes(search.toLowerCase()))
  const toggle = (task: CreationTask) => { const status = task.status === 'Paused' ? 'Running' : 'Paused'; patch({ creationTasks: state.creationTasks.map(item => item.id === task.id ? { ...item, status } : item) }); notify(tr(`${task.name} is now ${status.toLowerCase()}`)) }
  const duplicate = (task: CreationTask, event: React.MouseEvent) => { event.stopPropagation(); onCreateTask(task) }
  return <div className="content-stack"><section className="section-row"><div><h2>{tr('Automatic Creation')}</h2><p>{tr('Each task is explicit about the question set and instruction inputs it will use.')}</p></div><button className="button button-primary" onClick={onCreate}><Plus size={15} /> {tr('Create task')}</button></section><Toolbar search={search} setSearch={setSearch} /><div className="task-grid">{tasks.map(task => <article className={`card task-card ${task.model && task.model !== 'Local simulation' ? 'task-card-clickable' : ''}`} key={task.id} onClick={() => task.model && task.model !== 'Local simulation' ? onInspectTask(task.id) : undefined} role={task.model && task.model !== 'Local simulation' ? 'button' : undefined} tabIndex={task.model && task.model !== 'Local simulation' ? 0 : undefined}><div className="task-head"><div><span className="eyebrow">{tr('TASK')} · {tr(task.status).toUpperCase()}</span><h3>{tr(task.name)}</h3></div><button className="icon-button" aria-label={tr(`Duplicate ${task.name}`)} onClick={event => duplicate(task, event)}><MoreHorizontal size={16} /></button></div><p className="task-keyword"><Tag size={14} /> {tr(task.keyword)} <span>· {task.questionCount} {tr('questions')}</span></p><div className="task-inputs"><span><PenLine size={13} />{tr(task.writingInstruction)}</span><span><FileText size={13} />{tr(task.titleInstruction)}</span><span><Database size={13} />{tr(task.knowledgeBase)}</span><span><Image size={13} />{tr(task.imageLibrary)}</span></div><div className="task-progress"><div><span>{tr('Generated')}</span><strong>{task.generated} / {task.target}</strong></div><div className="progress"><span style={{ width: `${task.target ? Math.min(100, task.generated / task.target * 100) : 0}%` }} /></div></div><div className="task-foot"><small>{tr('Updated')} {tr(task.updated)}</small><div><span className={`status-pill ${task.status.toLowerCase()}`}>{tr(task.status)}</span><button className="button button-small button-outline" onClick={event => { event.stopPropagation(); toggle(task) }}>{tr(task.status === 'Paused' ? 'Resume' : 'Pause')}</button>{task.model && task.model !== 'Local simulation' && <button className="button button-small button-primary" onClick={event => { event.stopPropagation(); notify(tr('Live agent request queued locally')) }}>{tr('Call live agent')}</button>}</div></div></article>)}</div>{!tasks.length && <p>{tr('No creation tasks match this search.')}</p>}</div>
}

export function CreationTaskModal({ initialMode, seed, state, patch, onClose, notify }: { initialMode: 'create' | 'duplicate' | 'inspect'; seed: CreationTask | null; state: AppState; patch: Patch; onClose: () => void; notify: (message: string) => void }) {
  const { t: tr } = useTranslation(); const [editing, setEditing] = useState(initialMode === 'create' || initialMode === 'duplicate'); const readOnly = initialMode === 'inspect' && !editing
  const [name, setName] = useState(initialMode === 'duplicate' && seed ? `${seed.name} copy` : seed?.name || '')
  const [model, setModel] = useState(seed?.model || 'Local simulation'); const [keywordSet, setKeywordSet] = useState(seed?.keyword || ''); const [target, setTarget] = useState(String(seed?.target || 10)); const [writingInstruction, setWritingInstruction] = useState(seed?.writingInstruction || 'Long-form standard'); const [titleInstruction, setTitleInstruction] = useState(seed?.titleInstruction || 'Question-led headline')
  const title = initialMode === 'inspect' ? (editing ? 'Edit creation task' : 'Inspect creation task') : initialMode === 'duplicate' ? 'Duplicate creation task' : 'Create automatic task'
  const submit = (event: FormEvent) => { event.preventDefault(); if (!name.trim()) return; const quantity = Math.max(1, Number(target) || 1); if (initialMode === 'duplicate' && seed) { const copy: CreationTask = { ...seed, id: uid('ct'), name: name.trim(), target: quantity, generated: 0, status: 'Ready', updated: 'just now' }; patch({ creationTasks: [copy, ...state.creationTasks] }); notify(tr('Duplicated configuration is ready for local review.')) } else if (seed) { const value = { ...seed, name: name.trim(), model, keyword: keywordSet.trim() || seed.keyword, target: quantity, writingInstruction, titleInstruction, updated: 'just now' }; patch({ creationTasks: state.creationTasks.map(item => item.id === seed.id ? value : item) }); notify(tr('Creation task updated locally')) } else { const value: CreationTask = { id: uid('ct'), name: name.trim(), model, keyword: keywordSet.trim() || 'new content theme', questionCount: 0, writingInstruction, titleInstruction, knowledgeBase: 'Product Library', imageLibrary: 'Brand Kit', generated: 0, target: quantity, status: 'Ready', updated: 'just now', localOnly: true, logs: [] }; patch({ creationTasks: [value, ...state.creationTasks] }); notify(tr('Creation task created locally')) } onClose() }
  return <Modal title={title} onClose={onClose} headerAction={readOnly ? <button className="button button-primary button-small" onClick={() => setEditing(true)}><PenLine size={14} /> {tr('Edit')}</button> : undefined}><form onSubmit={submit}><label>{tr('Task name')}<input autoFocus disabled={readOnly} value={name} onChange={event => setName(event.target.value)} /></label><label>{tr('Model label')}<input disabled={readOnly} value={model} onChange={event => setModel(event.target.value)} /></label><label>{tr('Keyword Set / question pool')}<input disabled={readOnly} value={keywordSet} onChange={event => setKeywordSet(event.target.value)} /></label><label>{tr('Target quantity')}<input type="number" min="1" disabled={readOnly} value={target} onChange={event => setTarget(event.target.value)} /></label><label>{tr('Writing instruction · body')}<input disabled={readOnly} value={writingInstruction} onChange={event => setWritingInstruction(event.target.value)} /></label><label>{tr('Title instruction')}<input disabled={readOnly} value={titleInstruction} onChange={event => setTitleInstruction(event.target.value)} /></label><div className="modal-foot"><button type="button" className="button button-outline" onClick={onClose}>{tr(readOnly ? 'Close' : 'Cancel')}</button>{!readOnly && <button className="button button-primary" type="submit"><Check size={15} /> {tr(initialMode === 'duplicate' ? 'Create duplicated task' : initialMode === 'inspect' ? 'Save changes' : 'Create task')}</button>}</div></form></Modal>
}

