import { BrainCircuit, Info, Plus, ShieldCheck } from 'lucide-react'
import { useState } from 'react'
import type { AppState, LedgerEntry } from '../../data'
import { useTranslation } from '../../i18n'
import { uid } from '../../utils'

export function PointsPage({ state, patch, notify }: { state: AppState; patch: (next: Partial<AppState>) => void; notify: (message: string) => void }) {
  const { t: tr } = useTranslation(); const [amount, setAmount] = useState('500')
  const recharge = () => { const value = Math.max(0, Number(amount) || 0); if (!value) return notify(tr('Enter a points amount first')); const entry: LedgerEntry = { id: uid('led'), type: 'Recharge', detail: 'Simulated manual recharge', amount: value, balance: state.balance + value, date: 'just now' }; patch({ balance: state.balance + value, ledger: [entry, ...state.ledger] }); notify(tr(`${value.toLocaleString()} points simulated`)) }
  return <div className="content-stack"><section className="points-hero card"><div><span className="eyebrow">{tr('AVAILABLE BALANCE')}</span><strong>{state.balance.toLocaleString()}</strong><p>{tr('Compute points are demo credits used to illustrate generation and validation consumption. They have no monetary value.')}</p></div><div className="recharge-box"><label>{tr('Simulate recharge')}<input inputMode="numeric" value={amount} onChange={e => setAmount(e.target.value)} /></label><button className="button button-primary" onClick={recharge}><Plus size={15} /> {tr('Add points')}</button><small>{tr('Explicitly simulated · no payment or billing')}</small></div></section><div className="info-grid points-explainer"><article className="card info-card"><span><BrainCircuit size={18} /></span><h3>{tr('Generation')}</h3><p>{tr('One question or article action can spend points in a real workspace. This demo only records sample usage.')}</p></article><article className="card info-card"><span><ShieldCheck size={18} /></span><h3>{tr('Validation')}</h3><p>{tr('Model checks use points in the simulated ledger to make operational costs visible.')}</p></article><article className="card info-card"><span><Info size={18} /></span><h3>{tr('Safe by design')}</h3><p>{tr('There is no payment provider, account connection, or external points system attached.')}</p></article></div><section className="card table-card"><div className="table-toolbar"><div><h2>{tr('Recent ledger')}</h2><p className="toolbar-subtitle">{tr('Local balance movements')}</p></div></div><div className="table-scroll"><table><thead><tr><th>{tr('Type')}</th><th>{tr('Detail')}</th><th>{tr('Amount')}</th><th>{tr('Balance')}</th><th>{tr('Date')}</th></tr></thead><tbody>{state.ledger.map(item => <tr key={item.id}><td><span className="ledger-type">{tr(item.type)}</span></td><td>{tr(item.detail)}</td><td className={item.amount > 0 ? 'positive' : ''}>{item.amount > 0 ? '+' : ''}{item.amount}</td><td>{item.balance}</td><td>{tr(item.date)}</td></tr>)}</tbody></table></div></section></div>
}

