import { Check, PenLine, Plus } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import type { AppState, WritingInstruction } from '../../data'
import { Modal, Toolbar } from '../../shared'
import { useTranslation } from '../../i18n'
import { formatDate, uid } from '../../utils'

export function InstructionsPage({ state, patch, notify, onCreate, onInspect }: { state: AppState; patch: (next: Partial<AppState>) => void; notify: (message: string) => void; onCreate: () => void; onInspect: (item: WritingInstruction) => void }) {
  const { t: tr } = useTranslation(); const [group, setGroup] = useState<'All' | WritingInstruction['group']>('All'); const [search, setSearch] = useState(''); const filtered = state.instructions.filter(item => (group === 'All' || item.group === group) && `${item.title} ${item.description}`.toLowerCase().includes(search.toLowerCase()))
  return <div className="content-stack"><div className="segmented">{(['All', 'Article', 'Title', 'Traffic Replication'] as const).map(name => <button key={name} className={group === name ? 'active' : ''} onClick={() => setGroup(name)}>{tr(name)} {name === 'All' && <b>{state.instructions.length}</b>}</button>)}<span className="segmented-spacer" /><button className="button button-primary" onClick={onCreate}><Plus size={15} /> {tr('New instruction')}</button></div><Toolbar search={search} setSearch={setSearch} /><div className="instruction-list">{filtered.map(item => <article className="card instruction-card instruction-card-clickable" key={item.id} onClick={() => onInspect(item)} role="button" tabIndex={0}><span className="instruction-icon"><PenLine size={16} /></span><div className="instruction-content"><div className="asset-title"><h3>{tr(item.title)}</h3><span className={`status-pill ${item.status.toLowerCase()}`}>{tr(item.status)}</span></div><p>{tr(item.description)}</p><small>{tr('Updated')} {tr(item.updated)}</small></div></article>)}</div></div>
}

export function InstructionModal({ initialMode, seed, state, patch, onClose, notify }: { initialMode: 'create' | 'inspect'; seed: WritingInstruction | null; state: AppState; patch: (next: Partial<AppState>) => void; onClose: () => void; notify: (message: string) => void }) {
  const { t: tr } = useTranslation(); const [mode, setMode] = useState(initialMode); const [title, setTitle] = useState(seed?.title || ''); const [group, setGroup] = useState<WritingInstruction['group']>(seed?.group || 'Article'); const [status, setStatus] = useState<WritingInstruction['status']>(seed?.status || 'Draft'); const [description, setDescription] = useState(seed?.description || ''); const readOnly = mode === 'inspect'
  const submit = (event: FormEvent) => { event.preventDefault(); if (!title.trim()) return; const value: WritingInstruction = { id: seed?.id || uid('wi'), title: title.trim(), group, status, description: description.trim() || 'Reusable local writing guidance.', updated: formatDate() }; patch({ instructions: seed ? state.instructions.map(item => item.id === seed.id ? value : item) : [value, ...state.instructions] }); notify(tr(seed ? 'Writing instruction saved locally' : 'Writing instruction created locally')); onClose() }
  return <Modal title={readOnly ? 'Inspect writing instruction' : seed ? 'Edit writing instruction' : 'Create writing instruction'} onClose={onClose} headerAction={readOnly ? <button className="button button-primary button-small" onClick={() => setMode('create')}><PenLine size={14} /> {tr('Edit')}</button> : undefined}><form className="creation-form" onSubmit={submit}><label>{tr('Title')}<input autoFocus disabled={readOnly} value={title} onChange={event => setTitle(event.target.value)} /></label><label>{tr('Group')}<select disabled={readOnly} value={group} onChange={event => setGroup(event.target.value as WritingInstruction['group'])}><option>Article</option><option>Title</option><option>Traffic Replication</option></select></label><label>{tr('Status')}<select disabled={readOnly} value={status} onChange={event => setStatus(event.target.value as WritingInstruction['status'])}><option>Active</option><option>Draft</option></select></label><label>{tr('Description')}<textarea rows={5} disabled={readOnly} value={description} onChange={event => setDescription(event.target.value)} /></label><div className="modal-foot"><button type="button" className="button button-outline" onClick={onClose}>{tr(readOnly ? 'Close' : 'Cancel')}</button>{!readOnly && <button type="submit" className="button button-primary" disabled={!title.trim()}><Check size={15} /> {tr(seed ? 'Save changes' : 'Create instruction')}</button>}</div></form></Modal>
}

