import { ArrowUpRight, BookOpen, Check, ClipboardList, RefreshCw, ShieldCheck, Table2 } from 'lucide-react'
import { useState } from 'react'
import type { AppState } from '../../data'
import { models } from '../../data'
import { Kpi, Toolbar } from '../../shared'
import { useTranslation } from '../../i18n'

export function ValidationPage2({ state, patch, notify }: { state: AppState; patch: (next: Partial<AppState>) => void; notify: (message: string) => void }) {
  const { t: tr } = useTranslation(); const [model, setModel] = useState('All models'); const [search, setSearch] = useState(''); const [tab, setTab] = useState('All platforms'); const [running, setRunning] = useState(false); const filtered = state.validationResults.filter(item => (model === 'All models' || item.model === model) && (tab === 'All platforms' || item.platform === tab) && item.keyword.toLowerCase().includes(search.toLowerCase()))
  const run = () => { setRunning(true); window.setTimeout(() => { setRunning(false); patch({ validationResults: state.validationResults.map(item => item.id === 'vr-3' ? { ...item, score: Math.min(100, item.score + 4), status: 'Passed' } : item) }); notify(tr('Validation task completed locally')) }, 650) }
  const exportCsv = () => { const header = 'keyword,model,platform,score,citations,responseTime,status,checked'; const body = filtered.map(item => [item.keyword, item.model, item.platform, item.score, item.citations, item.responseTime, item.status, item.checked].map(value => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n'); const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(new Blob([`${header}\n${body}`], { type: 'text/csv;charset=utf-8' })); anchor.download = 'geoflow-model-validation.csv'; anchor.click(); notify(tr('CSV exported from the local validation table')) }
  return <div className="content-stack"><div className="kpi-grid compact-kpis"><Kpi label="Average quality" value="75.4" delta="+3.1 pts" icon={ShieldCheck} tone="green" /><Kpi label="Pass rate" value="67%" delta="4 of 6 checks" icon={Check} tone="cobalt" /><Kpi label="Citations / answer" value="4.5" delta="+0.8 this week" icon={BookOpen} tone="violet" /><Kpi label="Task queue" value="12" delta="Ready to run" icon={ClipboardList} tone="orange" /></div><div className="platform-tabs"><button className={tab === 'All platforms' ? 'active' : ''} onClick={() => setTab('All platforms')}>{tr('All platforms')}</button>{models.map(name => <button className={tab === name ? 'active' : ''} key={name} onClick={() => setTab(name)}>{name}</button>)}</div><Toolbar search={search} setSearch={setSearch} selects={<select aria-label={tr('Filter by model')} value={model} onChange={event => setModel(event.target.value)}><option>All models</option>{models.map(name => <option key={name}>{name}</option>)}</select>} action={<><button className="button button-outline" onClick={exportCsv}><Table2 size={15} /> {tr('Export CSV')}</button><button className="button button-primary" disabled={running} onClick={run}><RefreshCw size={15} /> {tr(running ? 'Running…' : 'Run task')}</button></>} /><section className="card table-card"><table><thead><tr><th>{tr('Question / keyword')}</th><th>{tr('Platform')}</th><th>{tr('Quality')}</th><th>{tr('Citations')}</th><th>{tr('Response')}</th><th>{tr('Status')}</th><th>{tr('Checked')}</th></tr></thead><tbody>{filtered.map(item => <tr key={item.id}><td>{item.keyword}</td><td>{item.platform}</td><td>{item.score}</td><td>{item.citations}</td><td>{item.responseTime}</td><td>{tr(item.status)}</td><td>{item.checked}</td></tr>)}</tbody></table><div className="table-footer"><span>{tr(`${filtered.length} validation results · simulated model output`)}</span><span>{tr('Task center')} <ArrowUpRight size={13} /></span></div></section></div>
}
