import { ArrowLeft, Image, Plus, Trash2 } from 'lucide-react'
import { useRef, useState } from 'react'
import type { AppState, ImageLibrary, LocalImage } from '../../data'
import type { Route } from '../../types'
import type { ConfirmRequest } from '../../shared/contracts'
import { EmptyState } from '../../shared'
import { useTranslation } from '../../i18n'
import { uid } from '../../utils'

export function ImageLibraryDetailPage({ imageLibrary, state, patch, navigate, notify, onBack, onConfirm }: { imageLibrary: ImageLibrary; state: AppState; patch: (next: Partial<AppState>) => void; navigate: (route: Route) => void; notify: (message: string) => void; onBack: () => void; onConfirm: (request: ConfirmRequest) => void }) {
  const { t: tr } = useTranslation(); const [addOpen, setAddOpen] = useState(false); const [name, setName] = useState(''); const [uploading, setUploading] = useState(false); const fileInputRef = useRef<HTMLInputElement>(null); const selected = imageLibrary.selectedImageIds || []
  const add = () => { const created: LocalImage = { id: uid('image'), name: name.trim() || `local-sample-${imageLibrary.images.length + 1}.png`, size: 240 * 1024, width: 1600, height: 1000, kind: 'sample', updated: 'just now' }; patch({ imageLibraries: state.imageLibraries.map(item => item.id === imageLibrary.id ? { ...item, images: [created, ...item.images], imageCount: item.images.length + 1, updated: 'just now' } : item) }); setName(''); setAddOpen(false); notify(tr('Local sample image added')) }
  const uploadFiles = async (files: FileList | null) => {
    if (!files?.length) return
    setUploading(true)
    const accepted: LocalImage[] = []
    for (const file of Array.from(files)) {
      if (!file.type.startsWith('image/') || file.size > 1024 * 1024) continue
      const dataUrl = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(reader.error); reader.readAsDataURL(file) })
      const dimensions = await new Promise<{ width: number; height: number }>(resolve => { const probe = new window.Image(); probe.onload = () => resolve({ width: probe.naturalWidth, height: probe.naturalHeight }); probe.onerror = () => resolve({ width: 0, height: 0 }); probe.src = dataUrl })
      accepted.push({ id: uid('image'), name: file.name, size: file.size, width: dimensions.width, height: dimensions.height, kind: 'uploaded', updated: 'just now', dataUrl })
    }
    if (accepted.length) { patch({ imageLibraries: state.imageLibraries.map(item => item.id === imageLibrary.id ? { ...item, images: [...accepted, ...item.images], imageCount: item.images.length + accepted.length, updated: 'just now' } : item) }); notify(tr(`${accepted.length} image${accepted.length === 1 ? '' : 's'} stored locally from your device`)) }
    setUploading(false); if (fileInputRef.current) fileInputRef.current.value = ''
  }
  const toggle = (id: string) => patch({ imageLibraries: state.imageLibraries.map(item => item.id === imageLibrary.id ? { ...item, selectedImageIds: selected.includes(id) ? selected.filter(value => value !== id) : [...selected, id] } : item) })
  const remove = (image: LocalImage) => onConfirm({ title: `Delete ${image.name}?`, action: () => { patch({ imageLibraries: state.imageLibraries.map(item => item.id === imageLibrary.id ? { ...item, images: item.images.filter(existing => existing.id !== image.id), selectedImageIds: selected.filter(id => id !== image.id), imageCount: Math.max(0, item.images.length - 1), updated: 'just now' } : item) }); notify(tr('Image deleted locally')) } })
  return <div className="kb-library-page image-library-detail-page"><div className="kb-library-toolbar"><button className="button button-outline" onClick={onBack}><ArrowLeft size={14} /> {tr('Back to image libraries')}</button></div><section className="kb-library-hero"><div><span className="eyebrow">{tr('IMAGE LIBRARY · LOCAL ALBUM')}</span><h2>{imageLibrary.name}</h2><p>{imageLibrary.description}</p></div><button className="button button-primary" onClick={() => setAddOpen(value => !value)}><Plus size={15} /> {tr('Add image')}</button></section>{addOpen && <section className="card image-add-panel"><div className="image-upload-zone"><strong>{tr('Upload from device')}</strong><input ref={fileInputRef} type="file" accept="image/*" multiple aria-label={tr('Upload images from device')} onChange={event => uploadFiles(event.target.files)} /><button type="button" className="button button-primary" onClick={() => fileInputRef.current?.click()} disabled={uploading}>{tr(uploading ? 'Reading files…' : 'Choose files')}</button></div><div className="image-add-divider"><span>{tr('or')}</span></div><label>{tr('Filename')}<input autoFocus placeholder={tr('e.g. workflow-note.png')} value={name} onChange={event => setName(event.target.value)} /></label><button className="button button-primary" onClick={add}><Plus size={14} /> {tr('Add sample placeholder')}</button></section>}{!imageLibrary.images.length ? <EmptyState title={tr('This album is empty')} text={tr('Add a local sample placeholder to make it available to task setup.')} /> : <div className="image-album-grid">{imageLibrary.images.map(image => <article className={`card image-album-card ${selected.includes(image.id) ? 'selected' : ''}`} key={image.id}><div className={`image-thumb ${image.dataUrl ? 'image-thumb-img-wrap' : ''}`}>{image.dataUrl ? <img src={image.dataUrl} alt={image.name} className="image-thumb-img" /> : <Image size={28} />}<span>{tr(image.kind === 'sample' ? 'Sample placeholder' : 'Uploaded from device')}</span></div><div className="image-album-body"><div className="image-card-title"><label><input type="checkbox" checked={selected.includes(image.id)} onChange={() => toggle(image.id)} /><strong>{image.name}</strong></label><button className="icon-button" aria-label={tr(`Delete ${image.name}`)} onClick={() => remove(image)}><Trash2 size={14} /></button></div><p>{Math.round(image.size / 1024)} KB · {image.width} × {image.height}px</p></div></article>)}</div>}<button className="button button-primary" disabled={!selected.length} onClick={() => navigate('automatic-creation')}>{tr('Use in automatic creation')}</button></div>
}
