import { ArrowUpRight, Cloud, Globe2, Plus, Search, ShieldCheck, Users } from 'lucide-react'
import { useState } from 'react'
import type { AppState, AccountConfig, InfluencerPartner, OperationsRecord, SeoCheck, WebsiteChannel } from '../../data'
import type { Route } from '../../types'
import { Toolbar } from '../../shared'
import { useTranslation } from '../../i18n'
import { uid } from '../../utils'

function Banner({ title, text }: { title: string; text: string }) { const { t: tr } = useTranslation(); return <section className="notice-banner compact-banner"><div className="notice-mark"><ShieldCheck size={17} /></div><div><strong>{title}</strong><p>{text}</p></div><span className="status-pill draft">{tr('Simulated · not connected')}</span></section> }
export function OperationsPage({ route, state, patch, notify }: { route: Route; state: AppState; patch: (next: Partial<AppState>) => void; notify: (message: string) => void }) {
  const { t: tr } = useTranslation(); const [search, setSearch] = useState('')
  if (route === 'records') { const records = state.records.filter(item => `${item.summary} ${item.owner}`.toLowerCase().includes(search.toLowerCase())); return <div className="content-stack"><Banner title={tr('Local operating records')} text={tr('A reviewable activity trail for the simulated workflow.')} /><Toolbar search={search} setSearch={setSearch} /><section className="card table-card"><table><thead><tr><th>{tr('Event')}</th><th>{tr('Type')}</th><th>{tr('Owner')}</th><th>{tr('Status')}</th><th>{tr('Date')}</th></tr></thead><tbody>{records.map((record: OperationsRecord) => <tr key={record.id}><td>{tr(record.summary)}</td><td>{tr(record.type)}</td><td>{tr(record.owner)}</td><td>{tr(record.status)}</td><td>{tr(record.date)}</td></tr>)}</tbody></table></section></div> }
  if (route === 'accounts') return <Accounts state={state} patch={patch} notify={notify} search={search} setSearch={setSearch} />
  if (route === 'website-media') return <Website state={state} patch={patch} notify={notify} />
  if (route === 'influencers') return <Influencers state={state} patch={patch} notify={notify} search={search} setSearch={setSearch} />
  const checks = state.seoChecks; return <div className="content-stack"><Banner title={tr('Official-site SEO workspace')} text={tr('Use these local checks to plan crawlability, schema, linking, and freshness work.')} /><div className="seo-grid">{checks.map((check: SeoCheck) => <article className="card seo-card" key={check.id}><div className="ops-card-top"><span className="eyebrow">{tr(check.area)}</span><span className="status-pill active">{tr(check.status)}</span></div><div className="seo-score"><strong>{check.score}</strong><div className="progress"><span style={{ width: `${check.score}%` }} /></div></div><p>{tr(check.note)}</p><button className="button button-small button-outline" onClick={() => { const next: SeoCheck['status'][] = ['Healthy', 'Needs review', 'Opportunity']; patch({ seoChecks: checks.map(item => item.id === check.id ? { ...item, status: next[(next.indexOf(check.status) + 1) % next.length] } : item) }); notify(tr('SEO status changed locally')) }}>{tr('Cycle status')}</button></article>)}</div></div>
}
function Accounts({ state, patch, notify, search, setSearch }: { state: AppState; patch: (next: Partial<AppState>) => void; notify: (message: string) => void; search: string; setSearch: (value: string) => void }) { const { t: tr } = useTranslation(); const [draft, setDraft] = useState(''); const accounts = state.accounts.filter(item => `${item.name} ${item.channel} ${item.owner}`.toLowerCase().includes(search.toLowerCase())); const add = () => { if (!draft.trim()) return; patch({ accounts: [{ id: uid('acct'), name: draft.trim(), type: 'CMS', channel: 'Website', status: 'Not connected', owner: 'Editorial team' }, ...state.accounts] }); setDraft(''); notify(tr('Account placeholder added locally')) }; return <div className="content-stack"><Banner title={tr('Account configuration placeholders')} text={tr('Configure channel ownership without storing credentials.')} /><Toolbar search={search} setSearch={setSearch} action={<div className="inline-create"><input value={draft} onChange={event => setDraft(event.target.value)} placeholder={tr('Account placeholder name')} /><button className="button button-primary" onClick={add}><Plus size={14} /> {tr('Add placeholder')}</button></div>} /><div className="ops-card-grid">{accounts.map((account: AccountConfig) => <article className="card ops-card" key={account.id}><Cloud size={17} /><h3>{tr(account.name)}</h3><p>{tr(account.type)} · {tr(account.channel)}</p><button className="button button-small button-outline" onClick={() => patch({ accounts: state.accounts.map(item => item.id === account.id ? { ...item, status: item.status === 'Configured' ? 'Not connected' : 'Configured' } : item) })}>{tr(account.status === 'Configured' ? 'Mark not connected' : 'Configure locally')}</button></article>)}</div></div> }
function Website({ state, patch, notify }: { state: AppState; patch: (next: Partial<AppState>) => void; notify: (message: string) => void }) { const { t: tr } = useTranslation(); const [name, setName] = useState(''); const [domain, setDomain] = useState(''); const add = () => { if (!name.trim() || !domain.trim()) return; patch({ websiteChannels: [{ id: uid('site'), name: name.trim(), domain: domain.trim(), contentType: 'Long-form article', approval: 'Manual', status: 'Draft', updated: 'just now' }, ...state.websiteChannels] }); setName(''); setDomain(''); notify(tr('Website channel added locally')) }; return <div className="content-stack"><Banner title={tr('Website media channels')} text={tr('Plan owned-site destinations and approval rules.')} /><section className="card inline-form-card"><div className="inline-form"><input aria-label={tr('Website channel name')} value={name} onChange={event => setName(event.target.value)} placeholder={tr('Channel name')} /><input aria-label={tr('Website path')} value={domain} onChange={event => setDomain(event.target.value)} placeholder={tr('example.local/resources')} /><button className="button button-primary" onClick={add}><Plus size={14} /> {tr('Add channel')}</button></div></section><div className="ops-card-grid">{state.websiteChannels.map((channel: WebsiteChannel) => <article className="card ops-card" key={channel.id}><Globe2 size={17} /><h3>{tr(channel.name)}</h3><p>{tr(channel.domain)}</p><button className="button button-small button-outline" onClick={() => patch({ websiteChannels: state.websiteChannels.map(item => item.id === channel.id ? { ...item, status: item.status === 'Ready' ? 'Draft' : 'Ready' } : item) })}>{tr(channel.status === 'Ready' ? 'Move to draft' : 'Mark ready')}</button></article>)}</div></div> }
function Influencers({ state, patch, notify, search, setSearch }: { state: AppState; patch: (next: Partial<AppState>) => void; notify: (message: string) => void; search: string; setSearch: (value: string) => void }) { const { t: tr } = useTranslation(); const [draft, setDraft] = useState(''); const partners = state.influencers.filter(item => `${item.name} ${item.focus} ${item.stage}`.toLowerCase().includes(search.toLowerCase())); const add = () => { if (!draft.trim()) return; patch({ influencers: [{ id: uid('inf'), name: draft.trim(), focus: 'New partner research', stage: 'Research', audience: 'Unverified', note: 'Local planning note' }, ...state.influencers] }); setDraft(''); notify(tr('Partner research record added locally')) }; return <div className="content-stack"><Banner title={tr('Partner distribution planning')} text={tr('Influencer records are planning notes only.')} /><Toolbar search={search} setSearch={setSearch} action={<div className="inline-create"><input value={draft} onChange={event => setDraft(event.target.value)} placeholder={tr('Partner or publication')} /><button className="button button-primary" onClick={add}><Plus size={14} /> {tr('Add research record')}</button></div>} /><div className="ops-card-grid">{partners.map((partner: InfluencerPartner) => <article className="card ops-card" key={partner.id}><Users size={17} /><h3>{tr(partner.name)}</h3><p>{tr(partner.focus)} · {tr(partner.audience)}</p><span className="status-pill draft">{tr(partner.stage)}</span></article>)}</div></div> }

